force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Voting Process</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Synopsis__c.field-meta.xml
<CustomField>
    <fullName>Synopsis__c</fullName>
    <label>Synopsis</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Upvotes__c.field-meta.xml
<CustomField>
    <fullName>Upvotes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Upvotes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProposalController.cls
public with sharing class ProposalController {

    @AuraEnabled(cacheable=true)
    public static List<Proposal__c> getProposalList(){
        return [
            select id, name, stage__c, synopsis__c, upvotes__c, owner.name from Proposal__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Proposal__c> getProposalList(String name, String stage){
        String searchterm = '%' + name + '%';
        
        if (name == '' & stage == ''){
            return [
                select id, name, stage__c, synopsis__c, upvotes__c, owner.name from Proposal__c
            ];
        } else if (name == ''){
            return [
                select id, name, stage__c, synopsis__c, upvotes__c, owner.name from Proposal__c
                where stage__c = :stage
            ];
        } else if (stage == ''){
            return [
                select id, name, stage__c, synopsis__c, upvotes__c, owner.name from Proposal__c
                where name like :searchterm
            ];
        } else {
            return [
            select id, name, stage__c, synopsis__c, upvotes__c, owner.name from Proposal__c
            where stage__c = :stage and name like :searchterm
        ];
        }
    }

    
}